[app]
GOOGLE_API_KEY = "AlzaSyAqQxXNtU1KUVOr4Cwr35y7XCUQ5ab_ds"
MONGODB_URI = "mongodb+srv://fatima:uxx4224xu@clusterfr.cz1mfei.mongodb.net/?appName=ClusterFR"
USER = "fatima"
COHERE_API_KEY = "FWD3TpfvKIaHrCZ6M3nc67svsB8MwnPNHx90XWCt"

[b2]
B2_BUCKET_NAME = "practica2-fr"
B2_READ_KEY_ID = "005ffc12281ab9b0000000003"
B2_READ_APPLICATION_KEY = "K0057AwaR0e67o5lVBsiCPt96ix1bZ4"
B2_WRITE_KEY_ID = "005ffc12281ab9b0000000002"
B2_WRITE_APPLICATION_KEY = "K005WajFi0XQmYfjzWxXol9pCnoRW1s"

