[app]
GOOGLE_API_KEY = ""
MONGODB_URI = ""
USER = "Juan Carlos Tovar Galarreta"
COHERE_API_KEY = ""

[b2]
B2_BUCKET_NAME = ""
B2_READ_KEY_ID = ""
B2_READ_APPLICATION_KEY = ""
B2_WRITE_KEY_ID = ""
B2_WRITE_APPLICATION_KEY = ""
